name: Cosmos DB Sync

on:
  push:
    branches:
      - 'main'
      - 'staging'

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install azure-cosmos
    
    - name: Sync to Cosmos DB
      env:
        COSMOS_ENDPOINT: ${{ secrets.COSMOS_ENDPOINT }}
        COSMOS_KEY: ${{ secrets.COSMOS_KEY }}
      run: |
        python sync-enrichment.py