name: Cosmos DB Sync

on:
  push:
    branches:
      - '*'

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install azure-cosmos
    
    - name: Sync to Cosmos DB
      run: |
        python sync.py