name: Cosmos DB Sync

on:
  push:
    branches:
      - 'main'
      - 'staging'

jobs:
  sync:
    runs-on: ubuntu-latest
    outputs:
        MODIFIED_FILES: ${{ steps.list_files.outputs.MODIFIED_FILES }}
    steps:
    - uses: actions/checkout@v3

    - name: List all modified json files
      id: list_files
      run: |
        list=$(git diff HEAD~ HEAD --name-only -- '*.json')
        echo "MODIFIED_FILES={$list}" >> $GITHUB_OUTPUT


    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install azure-cosmos
    
    - name: Sync to Cosmos DB
      env:
        COSMOS_ENDPOINT: ${{ secrets.COSMOS_ENDPOINT }}
        COSMOS_KEY: ${{ secrets.COSMOS_KEY }}
        MODIFIED_FILES: ${{ steps.list_files.outputs.MODIFIED_FILES }}
      run: |
        python syncer-enrichment.py