name: Cosmos DB Sync

on:
  push:
    branches:
      - '**'
      - '!main'
      - '!staging'

jobs:
  sync:
    runs-on: ubuntu-latest
    # outputs:
    #     MODIFIED_FILES: ${{ steps.list_files.outputs.modified_files }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # - name: List all modified JSON files
    #   id: list_files
    #   run: |
    #     file_list=()

    #     # Collect JSON files changed between the last two commits
    #     while IFS= read -r file; do
    #     file_list+=("$file")
    #     done < <(git diff --name-only HEAD~ HEAD | grep '\.json$')

    #     # Join the array elements into a comma-separated string
    #     IFS=',' read -r -a joined_files <<< "${file_list[*]}"

    #     # Export the list as a GitHub Actions output
    #     echo "MODIFIED_FILES=${joined_files[*]}" >> "$GITHUB_OUTPUT"

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install azure-cosmos
    
    - name: Sync to Cosmos DB
      env:
        COSMOS_ENDPOINT: ${{ secrets.COSMOS_ENDPOINT }}
        COSMOS_KEY: ${{ secrets.COSMOS_KEY }}
        MODIFIED_FILES: ${{ steps.list_files.outputs.modified_files }}
        COSMOS_DB_NAME: ${{ github.ref_name }}
      run: |
        python syncer-enrichment.py
